# Generated by Django 3.1.7 on 2021-03-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                default=20,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="auth.group",
                verbose_name="Group",
            ),
        ),
    ]
