# Generated by Django 3.1.7 on 2021-03-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backgroundimage",
            options={
                "verbose_name": "background image",
                "verbose_name_plural": "background images",
            },
        ),
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "verbose_name": "blog category",
                "verbose_name_plural": "blog categories",
            },
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={"verbose_name": "blog post", "verbose_name_plural": "blog posts"},
        ),
        migrations.AlterModelOptions(
            name="blogtag",
            options={"verbose_name": "blog tag", "verbose_name_plural": "blog tags"},
        ),
    ]
